language: java
jdk:
  - openjdk8

branches:
  only:
  - tutorials

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
    - funchcode@gmail.com